### ISSUE TITLE
where do i find the cookie for tiktok?

### ISSUE THREAD

**Issue by blxrryskies** [edde746/tiktok-askreddit#1]
i try to find the tiktok sent cookie header, but i cant find, could u tell me by any chance where it is? and after that, do i have to create a txt file named "tiktok.cookies"?

**Comment by edde746** [comment]
Yes, create a text file containing the cookie header copied from the request.
Step by step to finding cookie header:
1. Go to tiktok.com
2. Sign in
3. Open DevTools (Ctrl + Shift + I)
4. Go to network tab
5. Reload page
6. In the filter box type: `domain:tiktok.com`
7. Select any request, preferably the last one in the list
8. Scroll down to `Request Headers`
9. Find the `cookie` header, right click and press copy value
10. Paste this into the `tiktok.cookies` file (create it if you do not have it)

**Comment by verticalhost** [comment]
It's seems they change way you get that cookies

**Comment by edde746** [comment]
> It's seems they change way you get that cookies

Nope, it has not. Make sure the request is to the TikTok domain.

**Comment by pyrgasm** [comment]
Can you just tell us what cookies is the one used for account auth

**Comment by pyrgasm** [comment]
istead of copying the whole cookies we could just take that one and also does it change on every request?

**Comment by pyrgasm** [comment]
I tried many times i still cant get it to work it just doesnt login using the cookies
