### ISSUE TITLE
TypeError problem

### ISSUE THREAD

**Issue by YD-43** [edde746/tiktok-askreddit#15]
Im running the newest installed python (10.3 1520.0) and a fresh install of the requirements and ive tried every variation of new releases, including trying on two different computers running windows 10. the error im getting is `TypeError: expected str, bytes or os.PathLike object, not NoneType`

![image](https://user-images.githubusercontent.com/80468930/175118381-be6e0004-74da-4874-9120-c8aac447062a.png)

if anyone can tell me what im doing wrong that would be great

**Comment by edde746** [comment]
Chromedriver issue, could be one of many things including,

- Chrome / Chromedriver not being installed or failing to install
- Insufficient permission to download and run chromedriver
