### ISSUE TITLE
import edgeTTS ModuleNotFoundError: No module named 'edgeTTS'

### ISSUE THREAD

**Issue by owalida** [edde746/tiktok-askreddit#2]
Hi,
I followed all your instructions but keep getting this error.
I made a pip list and edgeTTS is installed but I still get this error 
`Traceback (most recent call last):
  File "C:\Users\User\Desktop\tiktok-askreddit-main\tiktok-askreddit-main\__main__.py", line 1, in <module>
    import asyncio,tts,os,video,requests
  File "C:\Users\User\Desktop\tiktok-askreddit-main\tiktok-askreddit-main\tts.py", line 2, in <module>
    import edgeTTS
ModuleNotFoundError: No module named 'edgeTTS'`

Do you know how can I fix this please ?

Thank you

**Comment by edde746** [comment]
Install the requirements, read the readme for instructions

**Comment by owalida** [comment]
Hi, the requirements are installed already.

**Comment by edde746** [comment]
> Hi, the requirements are installed already.

Did you run `pip install -r requirements.txt`?

**Comment by owalida** [comment]
Yes I did 


```
C:\Users\User\Desktop\tiktok-askreddit-main\tiktok-askreddit-main>pip install -r requirements.txt
Requirement already satisfied: selenium in c:\python39\lib\site-packages (from -r requirements.txt (line 1)) (3.141.0)
Requirement already satisfied: edge-tts in c:\python39\lib\site-packages (from -r requirements.txt (line 2)) (4.0.3)
Requirement already satisfied: moviepy in c:\python39\lib\site-packages (from -r requirements.txt (line 3)) (1.0.3)
Requirement already satisfied: requests in c:\python39\lib\site-packages (from -r requirements.txt (line 4)) (2.26.0)
Requirement already satisfied: webdriver-manager in c:\python39\lib\site-packages (from -r requirements.txt (line 5)) (3.5.2)
Requirement already satisfied: msedge-selenium-tools in c:\python39\lib\site-packages (from -r requirements.txt (line 6)) (3.141.4)
Requirement already satisfied: urllib3 in c:\python39\lib\site-packages (from selenium->-r requirements.txt (line 1)) (1.26.7)
Requirement already satisfied: aiohttp>=3.7.4.post0 in c:\python39\lib\site-packages (from edge-tts->-r requirements.txt (line 2)) (3.8.1)
Requirement already satisfied: decorator<5.0,>=4.0.2 in c:\python39\lib\site-packages (from moviepy->-r requirements.txt (line 3)) (4.4.2)
Requirement already satisfied: tqdm<5.0,>=4.11.2 in c:\python39\lib\site-packages (from moviepy->-r requirements.txt (line 3)) (4.62.3)
Requirement already satisfied: proglog<=1.0.0 in c:\python39\lib\site-packages (from moviepy->-r requirements.txt (line 3)) (0.1.9)
Requirement already satisfied: numpy>=1.17.3 in c:\python39\lib\site-packages (from moviepy->-r requirements.txt (line 3)) (1.21.4)
Requirement already satisfied: imageio<3.0,>=2.5 in c:\python39\lib\site-packages (from moviepy->-r requirements.txt (line 3)) (2.13.5)
Requirement already satisfied: imageio_ffmpeg>=0.2.0 in c:\python39\lib\site-packages (from moviepy->-r requirements.txt (line 3)) (0.4.5)
Requirement already satisfied: idna<4,>=2.5 in c:\python39\lib\site-packages (from requests->-r requirements.txt (line 4)) (3.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\python39\lib\site-packages (from requests->-r requirements.txt (line 4)) (2021.5.30)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\python39\lib\site-packages (from requests->-r requirements.txt (line 4)) (2.0.6)
Requirement already satisfied: crayons in c:\python39\lib\site-packages (from webdriver-manager->-r requirements.txt (line 5)) (0.4.0)
Requirement already satisfied: configparser in c:\python39\lib\site-packages (from webdriver-manager->-r requirements.txt (line 5)) (5.2.0)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in c:\python39\lib\site-packages (from aiohttp>=3.7.4.post0->edge-tts->-r requirements.txt (line 2)) (4.0.2)
Requirement already satisfied: attrs>=17.3.0 in c:\python39\lib\site-packages (from aiohttp>=3.7.4.post0->edge-tts->-r requirements.txt (line 2)) (21.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\python39\lib\site-packages (from aiohttp>=3.7.4.post0->edge-tts->-r requirements.txt (line 2)) (1.3.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\python39\lib\site-packages (from aiohttp>=3.7.4.post0->edge-tts->-r requirements.txt (line 2)) (6.0.2)
Requirement already satisfied: aiosignal>=1.1.2 in c:\python39\lib\site-packages (from aiohttp>=3.7.4.post0->edge-tts->-r requirements.txt (line 2)) (1.2.0)
Requirement already satisfied: yarl<2.0,>=1.0 in c:\python39\lib\site-packages (from aiohttp>=3.7.4.post0->edge-tts->-r requirements.txt (line 2)) (1.7.2)
Requirement already satisfied: pillow>=8.3.2 in c:\python39\lib\site-packages (from imageio<3.0,>=2.5->moviepy->-r requirements.txt (line 3)) (8.4.0)
Requirement already satisfied: colorama in c:\python39\lib\site-packages (from tqdm<5.0,>=4.11.2->moviepy->-r requirements.txt (line 3)) (0.4.4)
```

**Comment by edde746** [comment]
> Yes I did

You might have 2 different python installs and using the wrong one then, not really an issue with this code, this is the pip package in question that would be missing: https://pypi.org/project/edge-tts/

**Comment by owalida** [comment]
Hi, I downloaded this package edge-tts-4.0.3 and copy paste it on the folder C:\Python39\Lib\site-packages but the issue persist.
Do you know what I can do ?
Thank you

**Comment by owalida** [comment]
Well, that's weird because : 
C:\Users\User\Desktop\tiktok-askreddit-main\tiktok-askreddit-main>python --version
Python 3.9.7
C:\Users\User\Desktop\tiktok-askreddit-main\tiktok-askreddit-main>pip list
Package                    Version
-------------------------- ------------
aiohttp                    3.8.1
aiosignal                  1.2.0
altgraph                   0.17.2
appdirs                    1.4.4
async-generator            1.10
async-timeout              4.0.2
attrs                      21.2.0
Babel                      2.9.1
beautifulsoup4             4.10.0
bot-studio                 1.2.3
bs4                        0.0.1
cachetools                 5.0.0
certifi                    2021.5.30
cffi                       1.15.0
charset-normalizer         2.0.6
chromedriver-py            98.0.4758.48
click                      8.0.3
colorama                   0.4.4
coloredlogs                14.3
configparser               5.2.0
crayons                    0.4.0
cryptography               35.0.0
cssselect                  1.1.0
cycler                     0.11.0
decorator                  4.4.2
docopt                     0.6.2
edge-tts                   4.0.3
fake-useragent             0.1.11
fonttools                  4.28.2
frozenlist                 1.3.0
fs                         2.4.14
future                     0.18.2
google-api-core            2.4.0
google-api-python-client   2.36.0
google-auth                2.5.0
google-auth-httplib2       0.1.0
google-auth-oauthlib       0.4.6
googleapis-common-protos   1.54.0
gTTS                       2.2.3
h11                        0.12.0
httplib2                   0.20.2
humanfriendly              10.0
idna                       3.2
imageio                    2.13.5
imageio-ffmpeg             0.4.5
importlib-metadata         4.8.1
install                    1.3.4
instaloader                4.5.5
instalooter                2.4.4
kiwisolver                 1.3.2
lxml                       4.6.3
matplotlib                 3.5.0
moviepy                    1.0.3
mpmath                     1.2.1
msedge-selenium-tools      3.141.4
multidict                  6.0.2
mutagen                    1.45.1
Nuitka                     0.6.19.1
numpy                      1.21.4
oauthlib                   3.2.0
opencv-python              4.5.5.62
outcome                    1.1.0
packaging                  21.3
parse                      1.19.0
pefile                     2021.9.3
Pillow                     8.4.0
pip                        22.0.2
proglog                    0.1.9
protobuf                   3.14.0
pyasn1                     0.4.8
pyasn1-modules             0.2.8
pycparser                  2.21
pyee                       8.2.2
pyffmpeg                   2.1.0
pyinstaller                4.7
pyinstaller-hooks-contrib  2021.3
pyOpenSSL                  21.0.0
pyparsing                  3.0.6
PyPDF2                     1.26.0
pyppeteer                  0.2.6
pyquery                    1.4.3
pyreadline3                3.4.1
python-dateutil            2.8.1
pytz                       2021.3
pyusb                      1.2.1
pywin32-ctypes             0.2.0
requests                   2.26.0
requests-html              0.10.0
requests-oauthlib          1.3.1
rsa                        4.8
schedule                   0.6.0
selenium                   3.141.0
setuptools                 57.4.0
setuptools-scm             6.3.2
six                        1.16.0
sniffio                    1.2.0
sortedcontainers           2.4.0
soupsieve                  2.2.1
tenacity                   6.3.1
tkcalendar                 1.6.1
tomli                      1.2.2
tqdm                       4.62.3
trio                       0.19.0
trio-websocket             0.9.2
typing-extensions          3.10.0.2
uritemplate                4.1.1
urllib3                    1.26.7
verboselogs                1.7
w3lib                      1.22.0
webdriver-manager          3.5.2
websockets                 9.1
wsproto                    1.0.0
XlsxWriter                 3.0.2
yarl                       1.7.2
youtube-video-uploader-bot 1.0.0
z3-solver                  4.8.13.0
zipp                       3.6.0

**Comment by edde746** [comment]
Do you have multiple python installs? Make sure you are using the right pip. Edit: try running "pip3.9 list"

**Comment by owalida** [comment]
No only one python install.

C:\Users\User\Desktop\tiktok-askreddit-main\tiktok-askreddit-main>pip3.9 list
Package                    Version
-------------------------- ------------
aiohttp                    3.8.1
aiosignal                  1.2.0
altgraph                   0.17.2
appdirs                    1.4.4
async-generator            1.10
async-timeout              4.0.2
attrs                      21.2.0
Babel                      2.9.1
beautifulsoup4             4.10.0
bot-studio                 1.2.3
bs4                        0.0.1
cachetools                 5.0.0
certifi                    2021.5.30
cffi                       1.15.0
charset-normalizer         2.0.6
chromedriver-py            98.0.4758.48
click                      8.0.3
colorama                   0.4.4
coloredlogs                14.3
configparser               5.2.0
crayons                    0.4.0
cryptography               35.0.0
cssselect                  1.1.0
cycler                     0.11.0
decorator                  4.4.2
docopt                     0.6.2
edge-tts                   4.0.3
fake-useragent             0.1.11
fonttools                  4.28.2
frozenlist                 1.3.0
fs                         2.4.14
future                     0.18.2
google-api-core            2.4.0
google-api-python-client   2.36.0
google-auth                2.5.0
google-auth-httplib2       0.1.0
google-auth-oauthlib       0.4.6
googleapis-common-protos   1.54.0
gTTS                       2.2.3
h11                        0.12.0
httplib2                   0.20.2
humanfriendly              10.0
idna                       3.2
imageio                    2.13.5
imageio-ffmpeg             0.4.5
importlib-metadata         4.8.1
install                    1.3.4
instaloader                4.5.5
instalooter                2.4.4
kiwisolver                 1.3.2
lxml                       4.6.3
matplotlib                 3.5.0
moviepy                    1.0.3
mpmath                     1.2.1
msedge-selenium-tools      3.141.4
multidict                  6.0.2
mutagen                    1.45.1
Nuitka                     0.6.19.1
numpy                      1.21.4
oauthlib                   3.2.0
opencv-python              4.5.5.62
outcome                    1.1.0
packaging                  21.3
parse                      1.19.0
pefile                     2021.9.3
Pillow                     8.4.0
pip                        22.0.2
proglog                    0.1.9
protobuf                   3.14.0
pyasn1                     0.4.8
pyasn1-modules             0.2.8
pycparser                  2.21
pyee                       8.2.2
pyffmpeg                   2.1.0
pyinstaller                4.7
pyinstaller-hooks-contrib  2021.3
pyOpenSSL                  21.0.0
pyparsing                  3.0.6
PyPDF2                     1.26.0
pyppeteer                  0.2.6
pyquery                    1.4.3
pyreadline3                3.4.1
python-dateutil            2.8.1
pytz                       2021.3
pyusb                      1.2.1
pywin32-ctypes             0.2.0
requests                   2.26.0
requests-html              0.10.0
requests-oauthlib          1.3.1
rsa                        4.8
schedule                   0.6.0
selenium                   3.141.0
setuptools                 57.4.0
setuptools-scm             6.3.2
six                        1.16.0
sniffio                    1.2.0
sortedcontainers           2.4.0
soupsieve                  2.2.1
tenacity                   6.3.1
tkcalendar                 1.6.1
tomli                      1.2.2
tqdm                       4.62.3
trio                       0.19.0
trio-websocket             0.9.2
typing-extensions          3.10.0.2
uritemplate                4.1.1
urllib3                    1.26.7
verboselogs                1.7
w3lib                      1.22.0
webdriver-manager          3.5.2
websockets                 9.1
wsproto                    1.0.0
XlsxWriter                 3.0.2
yarl                       1.7.2
youtube-video-uploader-bot 1.0.0
z3-solver                  4.8.13.0
zipp                       3.6.0

**Comment by edde746** [comment]
https://github.com/rany2/edge-tts/issues/1
The issue is on your end and there is not much I can do, alternatively you can switch for another tts engine but it is not something that I will change.

**Comment by owalida** [comment]
Just to let you know that I found the issue.
On your tts.py in line 2 it says import edgetts
I modified it by import edge_tts and it's now working
but I face a new issue , it's says everytime
DevTools listening on ws://127.0.0.1:31742/devtools/browser/b589dc4e-8e09-49e2-aa65-8506887e08d1
❌ Failed to screenshot post!

**Comment by edde746** [comment]
> Just to let you know that I found the issue. On your tts.py in line 2 it says import edgetts I modified it by import edge_tts and it's now working but I face a new issue , it's says everytime DevTools listening on ws://127.0.0.1:31742/devtools/browser/b589dc4e-8e09-49e2-aa65-8506887e08d1 ❌ Failed to screenshot post!

On like 72 of scraper.py add `raise e` then create a new issue with that error
