### ISSUE TITLE
AttributeError? 

### ISSUE THREAD

**Issue by kingpinofsteel** [edde746/tiktok-askreddit#21]
![image](https://user-images.githubusercontent.com/89712959/187749469-a204b555-ffe9-4eb5-8f3c-da4a1193e492.png)
I know next to nothing about python. I just want to know why this is happening and how to fix it.

**Comment by edde746** [comment]
I am not actively maintaining this project, most likely the `find_element_by_css_selector` function got depreciated, either use an old version of Selenium or update the code to use the new function.

https://stackoverflow.com/questions/69875125/find-element-by-commands-are-deprecated-in-selenium
