### ISSUE TITLE
Is there a way to decode comments when scraping?

### ISSUE THREAD

**Issue by heensuk** [edde746/tiktok-askreddit#5]
I was wondering how to decode like \u00e7 'ç' and symbols like ' **´** ',**~**  and **^** when scraping comments.

**Comment by heensuk** [comment]
I don't know if it has to do with decode. I don't know how to fix it.
![image](https://user-images.githubusercontent.com/94083869/167077132-5cbbfe0c-619a-46a6-a841-299dac821c43.png)

The post title seems to not have this problem.

**Comment by edde746** [comment]
[Relevant code](https://github.com/edde746/tiktok-askreddit/blob/main/scraper.py#L61), possibly an issue with selenium/chromedriver

**Comment by heensuk** [comment]
If I print the [text](https://github.com/edde746/tiktok-askreddit/blob/8eec278250929f9f75b1b838a9ce1ff865ad62d5/scraper.py#L61) I don't get any issue.
![image](https://user-images.githubusercontent.com/94083869/167091329-41074531-a6c7-4343-a1a1-9a2b00cea9d4.png)

**Comment by heensuk** [comment]
I think the issue is on [this line](https://github.com/edde746/tiktok-askreddit/blob/8eec278250929f9f75b1b838a9ce1ff865ad62d5/scraper.py#L65) with 'string.printable' , if you know how to deal with it, please tell me.

**Comment by heensuk** [comment]
I just fixed in a horrible way. I just added the unicode letters like áàâ on string library.
