### ISSUE TITLE
Not working when posts have images?

### ISSUE THREAD

**Issue by kwonwoowoo** [edde746/tiktok-askreddit#9]
When a post has an image, it seems to create issues with the scraper file

**Comment by kwonwoowoo** [comment]
@edde746 Do you know if there's a fix for this? Something with selenium or the chrome driver?

**Comment by edde746** [comment]
> @edde746 Do you know if there's a fix for this? Something with selenium or the chrome driver?

I'm not actively maintaining this project, it was mostly just something I did for fun. My recommendation is that you learn to read error messages and how to code yourself.

You can see that it is timing out finding the post content, the easiest fix would probably just to add a fallback to try to get the image instead if it fails.
